### ISSUE TITLE
[Feat]: Add a clear and detailed guide on how to generate Monkeytype Readme for the first time.

### ISSUE THREAD

**Issue by Himanshuch8055** [monkeytype-hub/monkeytype-readme#44]
### Add a clear and detailed guide on how to generate Monkeytype Readme for the first time, as the current instructions are difficult to understand.

The user requested to add a clear and detailed guide on how to generate Monkeytype Readme for the first time, as the current instructions are difficult to understand.

**Comment by ridemountainpig** [comment]
Can you let me which part of the detail is not clear?

To create a Monkeytype readme, start by entering the `name`. Next, choose options for `leader board`, `personal best`, and `theme`. After making these selections, click the generate button. This action will produce two outputs: an SVG of the Monkeytype readme and the corresponding YML code. The SVG can be directly inserted into your readme file. Additionally, the YML code can be used to set up a GitHub Action. This action automatically updates the Monkeytype readme SVG in your repository.
